import { ChartDataPoint, LeadActivity, MetricData, AttentionLead, LiveConversation, Conversation, LeadDetail, PipelineLead, PipelineColumn } from './types'

// ============ MÉTRICAS GLOBALES UNIFICADAS ============
// Fuente única de verdad para todos los módulos

export const GLOBAL_STATS = {
  leads: {
    total: 1247,
    thisMonth: 352,
    thisWeek: 89,
    today: 28,
    nuevo: 405,
    contactado: 318,
    calificado: 524,
    visita: 156,
    reserva: 47,
  },
  conversaciones: {
    total: 3842,
    activas: 42,
    hoy: 156,
    cerradas: 3644,
  },
  tasas: {
    conversion: 42.0, // calificados/total = 524/1247
    contacto: 71.5, // contactados/total = 892/1247
    visita: 12.5, // visitas/total = 156/1247
    reserva: 3.8, // reservas/total = 47/1247
  },
  agentes: {
    emprendimientos: { conversations: 2156, qualified: 342, successRate: 94, avgTime: '1.2s' },
    inmuebles: { conversations: 1042, qualified: 126, successRate: 89, avgTime: '1.5s' },
    tasaciones: { conversations: 644, qualified: 56, successRate: 92, avgTime: '2.1s' },
  },
  fuentes: [
    { source: 'Instagram Ads', leads: 542, percentage: 43.5 },
    { source: 'Facebook Ads', leads: 312, percentage: 25.0 },
    { source: 'Google Ads', leads: 198, percentage: 15.9 },
    { source: 'Orgánico', leads: 124, percentage: 9.9 },
    { source: 'Referidos', leads: 71, percentage: 5.7 },
  ],
  proyectos: [
    { name: 'Roccatagliata', leads: 245, qualified: 98, reservas: 12, color: 'bg-blue-500' },
    { name: 'Voie Cañitas', leads: 189, qualified: 82, reservas: 8, color: 'bg-purple-500' },
    { name: 'Huergo 475', leads: 267, qualified: 112, reservas: 15, color: 'bg-emerald-500' },
    { name: 'Human Abasto', leads: 198, qualified: 86, reservas: 5, color: 'bg-amber-500' },
    { name: 'Joy Patagonia', leads: 156, qualified: 72, reservas: 4, color: 'bg-rose-500' },
    { name: 'BTN Pinamar', leads: 112, qualified: 48, reservas: 2, color: 'bg-cyan-500' },
    { name: 'Puerto Quetzal', leads: 80, qualified: 26, reservas: 1, color: 'bg-indigo-500' },
  ],
  semanal: [
    { week: 'Sem 1', leads: 280, qualified: 112, reservas: 8 },
    { week: 'Sem 2', leads: 320, qualified: 138, reservas: 12 },
    { week: 'Sem 3', leads: 295, qualified: 125, reservas: 10 },
    { week: 'Sem 4', leads: 352, qualified: 149, reservas: 17 },
  ],
  embudo: [
    { label: 'Leads', value: 1247, color: 'bg-blue-500' },
    { label: 'Contactados', value: 892, color: 'bg-purple-500' },
    { label: 'Calificados', value: 524, color: 'bg-emerald-500' },
    { label: 'Visitas', value: 156, color: 'bg-amber-500' },
    { label: 'Reservas', value: 47, color: 'bg-rose-500' },
  ],
}

// ============ EMPRENDIMIENTOS REALES ============
// Datos actualizados desde brochures oficiales de STAR Real Estate

export const EMPRENDIMIENTOS = {
  roccatagliata: {
    id: 'roccatagliata',
    name: 'Roccatagliata',
    location: 'Belgrano, CABA',
    description: 'Emplazado sobre un terreno de 3.500 m², conjugando la elegancia de la historia Argentina con la sofisticación de un proyecto moderno. Ubicación privilegiada frente a un palacio histórico con vistas panorámicas únicas.',
    features: ['Full Amenities', 'Locales Comerciales en PB', '180 Cocheras en 3 Subsuelos', 'Verdes jardines'],
    tipologias: [
      { ambientes: '2 Amb', superficie: '42-67 m² cubiertos', superficieTotal: '54-94 m²' },
      { ambientes: '3 Amb', superficie: '73-75 m² cubiertos', superficieTotal: '94 m²' },
      { ambientes: '4 Amb', superficie: '89-123 m² cubiertos', superficieTotal: '120-153 m²' },
      { ambientes: '4 Amb c/Dep', superficie: '116-121 m² cubiertos', superficieTotal: '146-149 m²' },
    ],
    tipologiasTexto: '1, 2, 3, 4 y 4 c/Dep desde 45 m² a 275 m²',
    priceRange: { min: 209657, max: 513876, currency: 'USD' },
    precioM2: { min: 2805, max: 4290, currency: 'USD' },
    unitsAvailable: 35,
    totalUnits: 120,
    estado: 'En construcción',
    entrega: '2026',
    contact: '11-6214-8113',
    web: 'www.starargentina.com',
    amenities: ['Piscina', 'SUM', 'Terraza', 'Gimnasio', 'Jardines'],
  },
  voie: {
    id: 'voie',
    name: 'Voie Cañitas',
    location: 'Cañitas, CABA',
    direccion: 'Ortega y Gasset 1920 / Baez 454',
    description: 'Conjunto edilicio de dos frentes sobre las calles Ortega y Gasset y Baez, formado por planta baja, 10 pisos y 3 subsuelos. Exclusivas unidades de viviendas familiares, local comercial, hall de acceso, amenities, cocheras, bauleras.',
    features: ['2 frentes', 'PB + 10 pisos + 3 subsuelos', 'Local comercial s/Baez', 'Cocheras y bauleras'],
    tipologias: [
      { ambientes: '2 Amb c/escritorio', superficie: '74-80 m² cubiertos', superficieTotal: '91-98 m²', unidades: 6 },
      { ambientes: '3 Amb', superficie: '82 m² cubiertos', superficieTotal: '102 m²', unidades: 6 },
      { ambientes: '4 Amb c/Dep', superficie: '121 m² cubiertos', superficieTotal: '146 m²', unidades: 6 },
      { ambientes: '5 Amb c/Dep', superficie: '155-202 m² cubiertos', superficieTotal: '220-251 m²', unidades: 4 },
    ],
    tipologiasTexto: '2 a 5 ambientes desde 91 m² a 251 m²',
    priceRange: { min: 180000, max: 450000, currency: 'USD' },
    unitsAvailable: 12,
    totalUnits: 22,
    estado: 'En construcción',
    contact: '11-6214-8113',
    web: 'www.starargentina.com',
    amenities: ['Piscina', 'Jacuzzi', 'Spa', 'Gym', 'Parrilla', 'S.U.M', 'Laundry'],
  },
  huergo: {
    id: 'huergo',
    name: 'Huergo 475',
    location: 'Puerto Madero, CABA',
    direccion: 'Paseo del Bajo | Dique 2 | Puerto Madero',
    description: 'Viví 365. Disfrutá 475. Frente al Paseo del Bajo y con vistas únicas de Buenos Aires. Con los mejores centros de estudio en un radio de 2 kilómetros. A diez cuadras de la Reserva Ecológica. A 750 metros del Puente de la Mujer. Y con el Río de la Plata siempre a la vista.',
    features: ['Vista al río', 'Frente al Paseo del Bajo', 'Cerca de Reserva Ecológica', 'Amenities premium'],
    tipologias: [
      { ambientes: '2 Amb', superficie: '~65 m²', superficieTotal: '~80 m²' },
      { ambientes: '3 Amb', superficie: '~90 m²', superficieTotal: '~110 m²' },
    ],
    tipologiasTexto: '2 y 3 ambientes (datos pendientes de brochure completo)',
    priceRange: { min: 285000, max: 650000, currency: 'USD' },
    unitsAvailable: 85,
    totalUnits: 200,
    estado: 'En construcción',
    contact: '11-6214-8113',
    web: 'www.starargentina.com',
    amenities: ['Piscina', 'Gym', 'SUM', 'Rooftop'],
    pendienteInfo: true, // Faltan datos del brochure
  },
  humanAbasto: {
    id: 'human-abasto',
    name: 'Human Abasto Towers',
    location: 'Balvanera, CABA',
    direccion: 'Calle Lavalle / Guardia Vieja',
    description: 'Un conjunto de residencias con amenities y áreas deportivas pensado para un público heterogéneo, diverso y consciente de la importancia que tiene el lugar en el que habitan. Vistas abiertas a la ciudad, balcones aterrazados y luz natural.',
    features: ['Entrega inmediata', 'Full amenities premium', 'Ideal alquileres temporarios', 'Torre Agüero disponible'],
    tipologias: [
      { ambientes: '3 Amb', superficie: '62-67 m² cubiertos', superficieTotal: '70-77 m²', balcon: '4-5 m²', amenities: '4-5 m²' },
    ],
    tipologiasTexto: '3 ambientes desde 70 m² a 77 m² totales',
    priceRange: { min: 171250, max: 207050, currency: 'USD' },
    ofertaEspecial: {
      descripcion: '4 unidades Torre Agüero a precio único',
      unidades: ['2003', '2302', '2303', '2403'],
      precioAnterior: 828198,
      precioOferta: 685000,
      currency: 'USD',
    },
    unitsAvailable: 4,
    totalUnits: 180,
    estado: 'Entrega inmediata',
    contact: '11-3556-5132',
    web: 'www.starargentina.com',
    amenities: ['Spa', 'Gym', 'Kids Club', 'Cowork Room', 'Laundry', 'Microcine', 'SUM Gourmet', 'Parrillas', 'Solarium', 'Parque de juegos', 'Sector chillout', 'Circuito aeróbico', 'Canchas de futbol/basquet/tenis', 'Piscina climatizada'],
  },
  joyPatagonia: {
    id: 'joy-patagonia',
    name: 'Joy Patagonia',
    location: 'El Calafate, Santa Cruz',
    description: 'Tan solo 27 residencias de 2 y 3 dormitorios que redefinen el concepto de vivir premium en El Calafate. Cada detalle está pensado para vivir una experiencia irrepetible. Diseñadas para maximizar las cautivadoras vistas al Lago Argentino, rodeado de un entorno naturalmente único. Inspirado en el concepto de "lujo esencial".',
    features: ['Vista Lago Argentino', '27 residencias exclusivas', '4 niveles', 'Terreno 27,440 m²', 'Calidad constructiva premium', 'Piso radiante', 'Madera Lenga'],
    tipologias: [
      { ambientes: '2 Dormitorios (Residencia Lago)', superficie: '89.50 m² cubiertos', superficieTotal: '123.5 m²', semicubierta: '34 m²' },
      { ambientes: '3 Dormitorios (Residencia Glaciar)', superficie: '120 m² cubiertos', superficieTotal: '168 m²', semicubierta: '48 m²' },
    ],
    tipologiasTexto: '2 y 3 dormitorios: 123.5 m² y 168 m²',
    priceRange: { min: 250000, max: 450000, currency: 'USD' },
    unitsAvailable: 18,
    totalUnits: 27,
    estado: 'En construcción',
    contact: '11-6214-8113',
    web: 'www.starargentina.com',
    amenities: ['Piscina climatizada', 'Spa', 'Hidromasaje', 'Sauna seco', 'Sauna húmedo', 'SUM con parrilla', 'Gimnasio', 'Restaurante', 'Cava de vinos', 'Terraza Sky Lounge'],
    desarrolladores: ['JOY Desarrollos', 'Patagonia Propiedades S.A.'],
    caracteristicas: {
      estructura: 'Platea de hormigón armado, construcción antisísmica, muros ladrillo cerámico 18x18x33',
      cubierta: 'Chapa acanalada pre pintada con aislación hidrófuga y térmica, cielorraso madera Lenga',
      solados: 'Porcelánico y SPC locking floor en dormitorios',
      calefaccion: 'Caldera mural a gas natural, piso radiante',
      aberturas: 'Aluminio con doble vidriado hermético',
    },
  },
  btnPinamar: {
    id: 'btn-pinamar',
    name: "B'Twins Norte",
    location: 'Pinamar, Costa Atlántica',
    description: 'Complejo de departamentos en Pinamar, ideal para inversión y disfrute de temporada.',
    features: ['Costa Atlántica', 'Ideal inversión', 'Temporada alta'],
    tipologias: [
      { ambientes: '1 Dormitorio', superficie: '~35 m²', superficieTotal: '~45 m²' },
      { ambientes: '2 Dormitorios', superficie: '~50 m²', superficieTotal: '~60 m²' },
    ],
    tipologiasTexto: '1 y 2 dormitorios (datos pendientes de brochure completo)',
    priceRange: { min: 85000, max: 150000, currency: 'USD' },
    unitsAvailable: 22,
    totalUnits: 48,
    estado: 'En construcción',
    contact: '11-6214-8113',
    web: 'www.starargentina.com',
    amenities: ['Piscina', 'Parrilla', 'Solarium'],
    pendienteInfo: true, // Faltan datos del brochure
  },
  puertoQuetzal: {
    id: 'puerto-quetzal',
    name: 'Puerto Quetzal',
    location: 'La Barra, Uruguay',
    direccion: 'Camino del Cerro Eguzquiza',
    description: 'Club de chacras que se encuentra a 5 minutos de La Barra, 25 minutos de Jose Ignacio, 2 minutos del Aeropuerto Fasano, 20 minutos de la Península y 2 hs de Montevideo. Un lugar natural y con una energía única. Exclusivo barrio privado con lotes de 4.000 m² para construir tu hogar en armonía con la naturaleza.',
    features: ['Lotes de 4.000 m²', 'Barrio privado', 'A 7 km de La Barra', 'A 15 min de Punta del Este', 'Seguridad', 'Naturaleza'],
    tipologias: [
      { tipo: 'Lote estándar', superficie: '4.000 m²' },
    ],
    tipologiasTexto: 'Lotes de 4.000 m² promedio',
    priceRange: { min: 150000, max: 350000, currency: 'USD' },
    lotesDisponibles: [
      { lote: 2, precio: 150000 },
      { lote: 6, precio: 280000 },
      { lote: 14, precio: 280000 },
      { lote: 16, precio: 280000 },
      { lote: 27, precio: 150000 },
      { lote: 34, precio: 250000 },
      { lote: 42, precio: 160000 },
      { lote: 47, precio: 150000 },
      { lote: 50, precio: 280000 },
      { lote: 57, precio: 280000 },
      { lote: 104, precio: 150000 },
      { lote: 116, precio: 280000 },
      { lote: 120, precio: 280000 },
      { lote: 135, precio: 350000 },
      { lote: 140, precio: 350000 },
      { lote: 155, precio: 160000 },
      { lote: 156, precio: 160000 },
      { lote: 158, precio: 160000 },
      { lote: 166, precio: 250000 },
      { lote: 173, precio: 250000 },
      { lote: 174, precio: 250000 },
      { lote: 180, precio: 170000 },
      { lote: 185, precio: 150000 },
      { lote: 186, precio: 150000 },
      { lote: 190, precio: 150000 },
      { lote: 194, precio: 300000 },
    ],
    financiacion: '50% en 18 cuotas mensuales sin intereses',
    unitsAvailable: 26,
    totalUnits: 200,
    estado: 'Disponible',
    contact: '11-6214-8113',
    web: 'www.starargentina.com',
    amenities: ['Club House', 'Seguridad 24hs', 'Entorno natural'],
  },
}

// ============ MÉTRICAS DASHBOARD (usando GLOBAL_STATS) ============

export const METRICS: MetricData[] = [
  {
    title: "Leads Totales",
    value: GLOBAL_STATS.leads.total.toLocaleString(),
    change: "+12.5%",
    isPositive: true,
  },
  {
    title: "Conversaciones Activas",
    value: GLOBAL_STATS.conversaciones.activas.toString(),
    change: "+8.3%",
    isPositive: true,
  },
  {
    title: "Tasa de Conversión",
    value: `${GLOBAL_STATS.tasas.conversion}%`,
    change: "+2.1%",
    isPositive: true,
  },
  {
    title: "Calificados Hoy",
    value: GLOBAL_STATS.leads.today.toString(),
    change: "",
    isPositive: true,
  },
]

export const CHART_DATA: ChartDataPoint[] = [
  { date: 'Ene 13', total: 145, qualified: 58 },
  { date: 'Ene 14', total: 168, qualified: 72 },
  { date: 'Ene 15', total: 142, qualified: 61 },
  { date: 'Ene 16', total: 128, qualified: 52 },
  { date: 'Ene 17', total: 175, qualified: 78 },
  { date: 'Ene 18', total: 156, qualified: 65 },
  { date: 'Ene 19', total: 189, qualified: 82 },
  { date: 'Ene 20', total: 144, qualified: 56 },
]

export const ATTENTION_LEADS: AttentionLead[] = [
  {
    id: '1',
    avatar: '',
    name: 'Juan Martinez',
    reason: 'human_requested',
    reasonText: 'Pidió hablar con humano',
    project: 'Roccatagliata',
    timeAgo: 'Hace 5 min',
    score: 85,
  },
  {
    id: '2',
    avatar: '',
    name: 'María López',
    reason: 'high_score',
    reasonText: 'Score 95, sin contactar',
    project: 'Huergo 475',
    timeAgo: 'Hace 2 horas',
    score: 95,
  },
  {
    id: '3',
    avatar: '',
    name: 'Carlos Ruiz',
    reason: 'no_response',
    reasonText: '2 días sin respuesta',
    project: 'Human Abasto',
    timeAgo: 'Hace 2 días',
    score: 72,
  },
]

export const LIVE_CONVERSATIONS: LiveConversation[] = [
  {
    id: '1',
    avatar: '',
    name: 'Juan Martinez',
    project: 'Roccatagliata',
    status: 'typing',
    lastActivity: 'Escribiendo...',
    agentType: 'emprendimientos',
  },
  {
    id: '2',
    avatar: '',
    name: 'Carlos López',
    project: 'Huergo 475',
    status: 'waiting',
    lastActivity: '2 min',
    agentType: 'emprendimientos',
  },
  {
    id: '3',
    avatar: '',
    name: 'Ana Rodríguez',
    project: 'Voie Cañitas',
    status: 'waiting',
    lastActivity: '5 min',
    agentType: 'emprendimientos',
  },
  {
    id: '4',
    avatar: '',
    name: 'Miguel Fernández',
    project: 'Tasación Belgrano',
    status: 'waiting',
    lastActivity: '8 min',
    agentType: 'tasaciones',
  },
]

export const RECENT_ACTIVITY: LeadActivity[] = [
  {
    id: '1',
    avatar: '',
    name: 'María González',
    project: 'Roccatagliata',
    action: 'Calificado',
    agent: { type: 'ai', name: 'Emp' },
    duration: '4.2 min',
    score: 92,
  },
  {
    id: '2',
    avatar: '',
    name: 'Juan Martinez',
    project: 'Huergo 475',
    action: 'Brochure enviado',
    agent: { type: 'ai', name: 'Emp' },
    duration: '1.5 min',
    score: 75,
  },
  {
    id: '3',
    avatar: '',
    name: 'Roberto Sánchez',
    project: 'Human Abasto',
    action: 'Visita agendada',
    agent: { type: 'human', name: 'Jony' },
    duration: '12 min',
    score: 95,
  },
  {
    id: '4',
    avatar: '',
    name: 'Ana Martínez',
    project: 'Voie Cañitas',
    action: 'Calificado',
    agent: { type: 'ai', name: 'Emp' },
    duration: '3.8 min',
    score: 88,
  },
  {
    id: '5',
    avatar: '',
    name: 'Laura Fernández',
    project: 'Roccatagliata',
    action: 'Tipología enviada',
    agent: { type: 'ai', name: 'Emp' },
    duration: '2.1 min',
    score: 67,
  },
]

// ============ INBOX DATA ============

export const CONVERSATIONS: Conversation[] = [
  {
    id: '1',
    leadId: 'lead-1',
    avatar: '',
    name: 'Juan Martinez',
    phone: '+54 11 4444-5555',
    project: 'Huergo 475',
    agentType: 'emprendimientos',
    status: 'needs_human',
    channel: 'whatsapp',
    lastMessage: 'Prefiero hablar con alguien del equipo',
    lastMessageTime: 'Hace 2 min',
    unread: true,
    isTyping: false,
    messages: [
      { id: 'm1', content: 'Hola! Vi el anuncio de Huergo 475 en Instagram', sender: 'lead', timestamp: '14:30' },
      { id: 'm2', content: '¡Hola Juan! 👋 Gracias por tu interés en Huergo 475. Es un proyecto premium en Puerto Madero con unidades de 2 y 3 ambientes con vista al río. ¿Qué tipo de unidad te interesa?', sender: 'ai', senderName: 'Agente Emp', timestamp: '14:30' },
      { id: 'm3', content: 'Me interesan los 3 ambientes, cuánto sale?', sender: 'lead', timestamp: '14:32' },
      { id: 'm4', content: 'Excelente elección! Los 3 ambientes arrancan en USD 285.000 y van hasta USD 450.000 según el piso y la vista. Tenemos opciones con vista al río y balcón terraza. ¿Te gustaría que te envíe el brochure con todas las tipologías?', sender: 'ai', senderName: 'Agente Emp', timestamp: '14:32' },
      { id: 'm5', content: 'Si, mandame', sender: 'lead', timestamp: '14:35' },
      { id: 'm6', content: '📎 Aquí tienes el brochure de Huergo 475. ¿Podemos coordinar una visita al showroom para que conozcas el proyecto en detalle?', sender: 'ai', senderName: 'Agente Emp', timestamp: '14:35' },
      { id: 'm7', content: 'Prefiero hablar con alguien del equipo', sender: 'lead', timestamp: '14:38' },
    ],
  },
  {
    id: '2',
    leadId: 'lead-2',
    avatar: '',
    name: 'Carlos López',
    phone: '+54 11 5555-6666',
    project: 'Joy Patagonia',
    agentType: 'emprendimientos',
    status: 'ai_active',
    channel: 'instagram',
    lastMessage: 'Cuántas cocheras tiene?',
    lastMessageTime: 'Hace 5 min',
    unread: true,
    isTyping: true,
    messages: [
      { id: 'm1', content: 'Hola, vi el emprendimiento Joy Patagonia', sender: 'lead', timestamp: '14:20' },
      { id: 'm2', content: '¡Hola Carlos! 🏔️ Joy Patagonia es nuestro desarrollo premium en El Calafate con 27 residencias exclusivas de 2 y 3 dormitorios, vista al Lago Argentino y full amenities incluyendo spa, piscina climatizada y restaurante con terraza sky lounge. ¿Buscás una propiedad para inversión o uso personal?', sender: 'ai', senderName: 'Agente Emp', timestamp: '14:20' },
      { id: 'm3', content: 'Para inversión, algo que se pueda alquilar en temporada', sender: 'lead', timestamp: '14:25' },
      { id: 'm4', content: 'Perfecto! Las residencias de 2 dormitorios (123.5 m²) son ideales para renta temporaria. Tenemos cochera incluida con cada unidad. ¿Te interesa conocer los valores?', sender: 'ai', senderName: 'Agente Emp', timestamp: '14:25' },
      { id: 'm5', content: 'Si dale. Cuántas cocheras tiene?', sender: 'lead', timestamp: '14:33' },
    ],
  },
  {
    id: '3',
    leadId: 'lead-3',
    avatar: '',
    name: 'Ana Rodríguez',
    phone: '+54 11 6666-7777',
    project: 'Voie Cañitas',
    agentType: 'emprendimientos',
    status: 'ai_active',
    channel: 'whatsapp',
    lastMessage: 'Tiene balcón?',
    lastMessageTime: 'Hace 1 hora',
    unread: false,
    isTyping: false,
    messages: [
      { id: 'm1', content: 'Hola, busco comprar en Cañitas', sender: 'lead', timestamp: '13:00' },
      { id: 'm2', content: '¡Hola Ana! 🏠 Tenemos Voie Cañitas en Ortega y Gasset 1920, un desarrollo de dos frentes con PB + 10 pisos. Amenities completos: Piscina, Jacuzzi, Spa, Gym, Parrilla, SUM y Laundry. ¿Qué cantidad de ambientes necesitás?', sender: 'ai', senderName: 'Agente Emp', timestamp: '13:00' },
      { id: 'm3', content: '2 ambientes, hasta 200 mil dólares', sender: 'lead', timestamp: '13:10' },
      { id: 'm4', content: 'Tenemos 2 ambientes con escritorio de 98 m² totales (74-80 m² cubiertos + 12 m² balcón + 6 m² amenities), muy luminosos. El rango de precios está dentro de tu presupuesto. ¿Te interesa?', sender: 'ai', senderName: 'Agente Emp', timestamp: '13:10' },
      { id: 'm5', content: 'Tiene balcón?', sender: 'lead', timestamp: '13:35' },
    ],
  },
  {
    id: '4',
    leadId: 'lead-4',
    avatar: '',
    name: 'Miguel Fernández',
    phone: '+54 11 7777-8888',
    project: 'Tasación Belgrano',
    agentType: 'tasaciones',
    status: 'ai_active',
    channel: 'whatsapp',
    lastMessage: 'Es un 4 ambientes con cochera',
    lastMessageTime: 'Hace 8 min',
    unread: false,
    isTyping: false,
    messages: [
      { id: 'm1', content: 'Hola, quiero tasar mi departamento', sender: 'lead', timestamp: '14:10' },
      { id: 'm2', content: '¡Hola Miguel! 📋 Con gusto te ayudamos con la tasación. ¿En qué barrio está ubicado el inmueble y qué tipo de propiedad es?', sender: 'ai', senderName: 'Agente Tas', timestamp: '14:10' },
      { id: 'm3', content: 'En Belgrano, cerca de Barrancas', sender: 'lead', timestamp: '14:15' },
      { id: 'm4', content: 'Excelente ubicación! ¿Cuántos ambientes tiene y cuenta con cochera o baulera?', sender: 'ai', senderName: 'Agente Tas', timestamp: '14:15' },
      { id: 'm5', content: 'Es un 4 ambientes con cochera', sender: 'lead', timestamp: '14:30' },
    ],
  },
  {
    id: '5',
    leadId: 'lead-5',
    avatar: '',
    name: 'Laura Gómez',
    phone: '+54 11 8888-9999',
    project: 'Roccatagliata',
    agentType: 'emprendimientos',
    status: 'closed',
    channel: 'facebook',
    lastMessage: 'Perfecto, nos vemos el jueves',
    lastMessageTime: 'Hace 3 horas',
    unread: false,
    isTyping: false,
    messages: [
      { id: 'm1', content: 'Info sobre Roccatagliata?', sender: 'lead', timestamp: '11:00' },
      { id: 'm2', content: '¡Hola Laura! 🏢 Roccatagliata es nuestro desarrollo premium en Belgrano sobre un terreno de 3.500 m². Full amenities, 180 cocheras, y unidades desde 1 a 4 ambientes (45 m² a 275 m²). Precios desde USD 209.657. ¿Qué tipo de unidad buscás?', sender: 'ai', senderName: 'Agente Emp', timestamp: '11:00' },
      { id: 'm3', content: '2 ambientes con balcón', sender: 'lead', timestamp: '11:15' },
      { id: 'm4', content: 'Tenemos 2 ambientes de 54 m² cubiertos con balcón desde USD 259.260. El precio por m² va de USD 3.850 a USD 4.290. ¿Te gustaría visitarlo? Tenemos disponibilidad esta semana.', sender: 'ai', senderName: 'Agente Emp', timestamp: '11:15' },
      { id: 'm5', content: 'Si, puede ser el jueves?', sender: 'lead', timestamp: '11:20' },
      { id: 'm6', content: '¡Perfecto! Te agendo para el jueves a las 15hs en nuestro showroom. Te envío la confirmación por WhatsApp. 📅', sender: 'human', senderName: 'Jony', timestamp: '11:25' },
      { id: 'm7', content: 'Perfecto, nos vemos el jueves', sender: 'lead', timestamp: '11:30' },
    ],
  },
  {
    id: '6',
    leadId: 'lead-6',
    avatar: '',
    name: 'Roberto Sánchez',
    phone: '+54 11 2222-3333',
    project: 'Human Abasto',
    agentType: 'emprendimientos',
    status: 'ai_active',
    channel: 'whatsapp',
    lastMessage: 'Qué financiación tienen?',
    lastMessageTime: 'Hace 15 min',
    unread: false,
    isTyping: false,
    messages: [
      { id: 'm1', content: 'Hola, vi Human Abasto en la web', sender: 'lead', timestamp: '14:00' },
      { id: 'm2', content: '¡Hola Roberto! 🏢 Human Abasto Towers está en Balvanera con entrega inmediata. Unidades de 3 ambientes de 70-77 m² totales. Tenemos una oferta especial: 4 unidades en Torre Agüero por USD 685.000 (antes USD 828.198). Full amenities premium incluido. ¿Te interesa?', sender: 'ai', senderName: 'Agente Emp', timestamp: '14:00' },
      { id: 'm3', content: 'Y por unidad sola? qué financiación tienen?', sender: 'lead', timestamp: '14:15' },
    ],
  },
]

export const LEAD_DETAILS: Record<string, LeadDetail> = {
  'lead-1': {
    id: 'lead-1',
    name: 'Juan Martinez',
    phone: '+54 11 4444-5555',
    email: 'juan.martinez@email.com',
    score: 85,
    interest: '3 ambientes vista río',
    budget: '285,000 - 450,000',
    budgetCurrency: 'USD',
    project: 'Huergo 475',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    createdAt: '20 Ene 2026',
    history: [
      { action: 'Primer contacto', date: '20 Ene 14:30', completed: true },
      { action: 'Brochure enviado', date: '20 Ene 14:35', completed: true },
      { action: 'Pidió humano', date: '20 Ene 14:38', completed: true },
      { action: 'Contactar', date: 'Pendiente', completed: false },
    ],
  },
  'lead-2': {
    id: 'lead-2',
    name: 'Carlos López',
    phone: '+54 11 5555-6666',
    email: 'carlos.lopez@email.com',
    score: 78,
    interest: '2 dorm inversión',
    budget: '250,000 - 300,000',
    budgetCurrency: 'USD',
    project: 'Joy Patagonia',
    agentType: 'emprendimientos',
    channel: 'instagram',
    createdAt: '20 Ene 2026',
    history: [
      { action: 'Primer contacto', date: '20 Ene 14:20', completed: true },
      { action: 'Calificación inicial', date: '20 Ene 14:25', completed: true },
      { action: 'Enviar tipologías', date: 'En proceso', completed: false },
    ],
  },
  'lead-3': {
    id: 'lead-3',
    name: 'Ana Rodríguez',
    phone: '+54 11 6666-7777',
    score: 72,
    interest: '2 amb con escritorio',
    budget: '200,000',
    budgetCurrency: 'USD',
    project: 'Voie Cañitas',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    createdAt: '20 Ene 2026',
    history: [
      { action: 'Primer contacto', date: '20 Ene 13:00', completed: true },
      { action: 'Info enviada', date: '20 Ene 13:10', completed: true },
      { action: 'Coordinar visita', date: 'Pendiente', completed: false },
    ],
  },
  'lead-4': {
    id: 'lead-4',
    name: 'Miguel Fernández',
    phone: '+54 11 7777-8888',
    email: 'miguel.f@email.com',
    score: 72,
    interest: 'Tasación 4 amb',
    project: 'Tasación Belgrano',
    agentType: 'tasaciones',
    channel: 'whatsapp',
    createdAt: '20 Ene 2026',
    history: [
      { action: 'Primer contacto', date: '20 Ene 14:10', completed: true },
      { action: 'Datos recopilados', date: '20 Ene 14:30', completed: true },
      { action: 'Agendar visita', date: 'Pendiente', completed: false },
    ],
  },
  'lead-5': {
    id: 'lead-5',
    name: 'Laura Gómez',
    phone: '+54 11 8888-9999',
    email: 'laura.gomez@email.com',
    score: 92,
    interest: '2 amb con balcón',
    budget: '259,260',
    budgetCurrency: 'USD',
    project: 'Roccatagliata',
    agentType: 'emprendimientos',
    channel: 'facebook',
    createdAt: '20 Ene 2026',
    history: [
      { action: 'Primer contacto', date: '20 Ene 11:00', completed: true },
      { action: 'Brochure enviado', date: '20 Ene 11:15', completed: true },
      { action: 'Visita agendada', date: '23 Ene 15:00', completed: true },
    ],
  },
  'lead-6': {
    id: 'lead-6',
    name: 'Roberto Sánchez',
    phone: '+54 11 2222-3333',
    email: 'roberto.sanchez@email.com',
    score: 68,
    interest: '3 amb',
    budget: '170,000',
    budgetCurrency: 'USD',
    project: 'Human Abasto',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    createdAt: '20 Ene 2026',
    history: [
      { action: 'Primer contacto', date: '20 Ene 14:00', completed: true },
      { action: 'Consulta financiación', date: '20 Ene 14:15', completed: true },
      { action: 'Responder', date: 'Pendiente', completed: false },
    ],
  },
}

// ============ PIPELINE DATA ============

export const PIPELINE_COLUMNS: PipelineColumn[] = [
  { id: 'nuevo', title: 'Nuevo', color: 'bg-gray-500' },
  { id: 'calificado', title: 'Calificado', color: 'bg-blue-500' },
  { id: 'contactado', title: 'Contactado', color: 'bg-purple-500' },
  { id: 'visita', title: 'Visita', color: 'bg-amber-500' },
  { id: 'cierre', title: 'Cierre', color: 'bg-emerald-500' },
]

export const PIPELINE_LEADS: PipelineLead[] = [
  // NUEVO (5)
  {
    id: 'pl-1',
    name: 'Martín Aguirre',
    phone: '+54 11 1111-2222',
    project: 'Roccatagliata',
    agentType: 'emprendimientos',
    channel: 'instagram',
    score: 45,
    interest: '2 ambientes',
    stage: 'nuevo',
    createdAt: '20 Ene 2026',
    lastActivity: 'Hace 10 min',
  },
  {
    id: 'pl-2',
    name: 'Sofía Peralta',
    phone: '+54 11 2222-3333',
    project: 'Huergo 475',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    score: 52,
    interest: '3 ambientes',
    stage: 'nuevo',
    createdAt: '20 Ene 2026',
    lastActivity: 'Hace 25 min',
  },
  {
    id: 'pl-3',
    name: 'Diego Romero',
    phone: '+54 11 3333-4444',
    project: 'Human Abasto',
    agentType: 'emprendimientos',
    channel: 'facebook',
    score: 38,
    interest: '3 ambientes',
    stage: 'nuevo',
    createdAt: '19 Ene 2026',
    lastActivity: 'Hace 1 hora',
  },
  {
    id: 'pl-4',
    name: 'Valentina Costa',
    phone: '+54 11 4444-5555',
    project: 'Voie Cañitas',
    agentType: 'emprendimientos',
    channel: 'instagram',
    score: 41,
    interest: '3 ambientes',
    stage: 'nuevo',
    createdAt: '19 Ene 2026',
    lastActivity: 'Hace 2 horas',
  },
  {
    id: 'pl-5',
    name: 'Nicolás Herrera',
    phone: '+54 11 5555-6666',
    project: 'Joy Patagonia',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    score: 55,
    interest: '2 dormitorios inversión',
    stage: 'nuevo',
    createdAt: '19 Ene 2026',
    lastActivity: 'Hace 3 horas',
  },
  // CALIFICADO (5)
  {
    id: 'pl-6',
    name: 'Juan Martinez',
    phone: '+54 11 4444-5555',
    email: 'juan.martinez@email.com',
    project: 'Huergo 475',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    score: 85,
    budget: '350,000',
    budgetCurrency: 'USD',
    interest: '3 amb vista río',
    stage: 'calificado',
    createdAt: '20 Ene 2026',
    lastActivity: 'Hace 5 min',
    notes: 'Pidió hablar con humano',
  },
  {
    id: 'pl-7',
    name: 'Carlos López',
    phone: '+54 11 5555-6666',
    email: 'carlos.lopez@email.com',
    project: 'Joy Patagonia',
    agentType: 'emprendimientos',
    channel: 'instagram',
    score: 78,
    budget: '280,000',
    budgetCurrency: 'USD',
    interest: '2 dorm inversión',
    stage: 'calificado',
    createdAt: '20 Ene 2026',
    lastActivity: 'Hace 5 min',
  },
  {
    id: 'pl-8',
    name: 'María López',
    phone: '+54 11 6666-7777',
    email: 'maria.lopez@email.com',
    project: 'Huergo 475',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    score: 95,
    budget: '450,000',
    budgetCurrency: 'USD',
    interest: '3 amb premium',
    stage: 'calificado',
    createdAt: '19 Ene 2026',
    lastActivity: 'Hace 2 horas',
    notes: 'Score alto, priorizar',
  },
  {
    id: 'pl-9',
    name: 'Ana Rodríguez',
    phone: '+54 11 6666-7777',
    project: 'Voie Cañitas',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    score: 72,
    budget: '200,000',
    budgetCurrency: 'USD',
    interest: '2 amb con escritorio',
    stage: 'calificado',
    createdAt: '20 Ene 2026',
    lastActivity: 'Hace 1 hora',
  },
  {
    id: 'pl-10',
    name: 'Pedro García',
    phone: '+54 11 7777-8888',
    email: 'pedro.garcia@email.com',
    project: 'Roccatagliata',
    agentType: 'emprendimientos',
    channel: 'facebook',
    score: 81,
    budget: '380,000',
    budgetCurrency: 'USD',
    interest: '4 amb con dep',
    stage: 'calificado',
    createdAt: '18 Ene 2026',
    lastActivity: 'Hace 1 día',
  },
  // CONTACTADO (3)
  {
    id: 'pl-11',
    name: 'Carlos Ruiz',
    phone: '+54 11 8888-9999',
    email: 'carlos.ruiz@email.com',
    project: 'Human Abasto',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    score: 72,
    budget: '170,000',
    budgetCurrency: 'USD',
    interest: '3 amb',
    stage: 'contactado',
    createdAt: '18 Ene 2026',
    lastActivity: 'Hace 2 días',
    assignedTo: 'Jony',
    notes: '2 días sin respuesta',
  },
  {
    id: 'pl-12',
    name: 'Roberto Sánchez',
    phone: '+54 11 2222-3333',
    email: 'roberto.sanchez@email.com',
    project: 'Human Abasto',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    score: 68,
    budget: '170,000',
    budgetCurrency: 'USD',
    interest: '3 amb',
    stage: 'contactado',
    createdAt: '20 Ene 2026',
    lastActivity: 'Hace 15 min',
    assignedTo: 'Jony',
  },
  {
    id: 'pl-13',
    name: 'Luciana Torres',
    phone: '+54 11 9999-0000',
    email: 'luciana.torres@email.com',
    project: "B'Twins Norte",
    agentType: 'emprendimientos',
    channel: 'instagram',
    score: 76,
    budget: '120,000',
    budgetCurrency: 'USD',
    interest: '2 dorm playa',
    stage: 'contactado',
    createdAt: '17 Ene 2026',
    lastActivity: 'Hace 1 día',
    assignedTo: 'María',
  },
  // VISITA (3)
  {
    id: 'pl-14',
    name: 'Laura Gómez',
    phone: '+54 11 8888-9999',
    email: 'laura.gomez@email.com',
    project: 'Roccatagliata',
    agentType: 'emprendimientos',
    channel: 'facebook',
    score: 92,
    budget: '259,260',
    budgetCurrency: 'USD',
    interest: '2 amb con balcón',
    stage: 'visita',
    createdAt: '20 Ene 2026',
    lastActivity: 'Hoy',
    assignedTo: 'Jony',
    scheduledDate: '23 Ene 15:00',
    notes: 'Visita confirmada',
  },
  {
    id: 'pl-15',
    name: 'Miguel Fernández',
    phone: '+54 11 7777-8888',
    email: 'miguel.f@email.com',
    project: 'Tasación Belgrano',
    agentType: 'tasaciones',
    channel: 'whatsapp',
    score: 72,
    interest: 'Tasación 4 amb',
    stage: 'visita',
    createdAt: '20 Ene 2026',
    lastActivity: 'Hace 8 min',
    assignedTo: 'Pablo',
    scheduledDate: '22 Ene 10:00',
    notes: 'Coordinar visita tasación',
  },
  {
    id: 'pl-16',
    name: 'Fernando Díaz',
    phone: '+54 11 1234-5678',
    email: 'fernando.diaz@email.com',
    project: 'Voie Cañitas',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    score: 88,
    budget: '280,000',
    budgetCurrency: 'USD',
    interest: '3 amb con terraza',
    stage: 'visita',
    createdAt: '16 Ene 2026',
    lastActivity: 'Ayer',
    assignedTo: 'Jony',
    scheduledDate: '24 Ene 16:00',
    notes: 'Segunda visita programada',
  },
  // CIERRE (2)
  {
    id: 'pl-17',
    name: 'María González',
    phone: '+54 11 5678-1234',
    email: 'maria.gonzalez@email.com',
    project: 'Roccatagliata',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    score: 98,
    budget: '380,000',
    budgetCurrency: 'USD',
    interest: '3 amb piso alto',
    stage: 'cierre',
    createdAt: '10 Ene 2026',
    lastActivity: 'Hoy',
    assignedTo: 'Jony',
    notes: 'Firma de boleto viernes',
  },
  {
    id: 'pl-18',
    name: 'Alejandro Vega',
    phone: '+54 11 8765-4321',
    email: 'alejandro.vega@email.com',
    project: 'Huergo 475',
    agentType: 'emprendimientos',
    channel: 'instagram',
    score: 96,
    budget: '520,000',
    budgetCurrency: 'USD',
    interest: '4 amb vista panorámica',
    stage: 'cierre',
    createdAt: '8 Ene 2026',
    lastActivity: 'Ayer',
    assignedTo: 'María',
    notes: 'Negociando condiciones de pago',
  },
]
