import { ChartDataPoint, LeadActivity, MetricData, AttentionLead, LiveConversation, Conversation, LeadDetail } from './types'

export const METRICS: MetricData[] = [
  {
    title: "Leads Totales",
    value: "127,482",
    change: "+23%",
    isPositive: true,
  },
  {
    title: "Conversaciones Activas",
    value: "42",
    change: "+4%",
    isPositive: true,
  },
  {
    title: "Tasa de Conversión",
    value: "68.7%",
    change: "+0.4%",
    isPositive: true,
  },
  {
    title: "Calificados Hoy",
    value: "18",
    change: "",
    isPositive: true,
  },
]

export const CHART_DATA: ChartDataPoint[] = [
  { date: 'Dic 1', total: 4000, qualified: 2400 },
  { date: 'Dic 5', total: 5800, qualified: 3200 },
  { date: 'Dic 8', total: 4200, qualified: 3800 },
  { date: 'Dic 12', total: 2800, qualified: 2100 },
  { date: 'Dic 15', total: 5100, qualified: 2800 },
  { date: 'Dic 22', total: 4500, qualified: 2100 },
  { date: 'Dic 26', total: 6800, qualified: 4200 },
  { date: 'Dic 29', total: 5900, qualified: 5100 },
]

export const ATTENTION_LEADS: AttentionLead[] = [
  {
    id: '1',
    avatar: 'https://picsum.photos/40/40?random=10',
    name: 'Juan Martinez',
    reason: 'human_requested',
    reasonText: 'Pidió hablar con humano',
    project: 'Roccatagliata',
    timeAgo: 'Hace 5 min',
    score: 85,
  },
  {
    id: '2',
    avatar: 'https://picsum.photos/40/40?random=11',
    name: 'María López',
    reason: 'high_score',
    reasonText: 'Score 95, sin contactar',
    project: 'Huergo 475',
    timeAgo: 'Hace 2 horas',
    score: 95,
  },
  {
    id: '3',
    avatar: 'https://picsum.photos/40/40?random=12',
    name: 'Carlos Ruiz',
    reason: 'no_response',
    reasonText: '2 días sin respuesta',
    project: 'Human Abasto',
    timeAgo: 'Hace 2 días',
    score: 72,
  },
]

export const LIVE_CONVERSATIONS: LiveConversation[] = [
  {
    id: '1',
    avatar: 'https://picsum.photos/32/32?random=20',
    name: 'Juan',
    project: 'Roccatagliata',
    status: 'typing',
    lastActivity: 'Escribiendo...',
    agentType: 'emprendimientos',
  },
  {
    id: '2',
    avatar: 'https://picsum.photos/32/32?random=21',
    name: 'Carlos',
    project: 'Huergo 475',
    status: 'waiting',
    lastActivity: '2 min',
    agentType: 'emprendimientos',
  },
  {
    id: '3',
    avatar: 'https://picsum.photos/32/32?random=22',
    name: 'Ana',
    project: 'Palermo Soho',
    status: 'waiting',
    lastActivity: '5 min',
    agentType: 'inmuebles',
  },
  {
    id: '4',
    avatar: 'https://picsum.photos/32/32?random=23',
    name: 'Miguel',
    project: 'Tasación Belgrano',
    status: 'waiting',
    lastActivity: '8 min',
    agentType: 'tasaciones',
  },
]

export const RECENT_ACTIVITY: LeadActivity[] = [
  {
    id: '1',
    avatar: 'https://picsum.photos/32/32?random=1',
    name: 'María González',
    project: 'Roccatagliata',
    action: 'Calificado',
    agent: { type: 'ai', name: 'Emp' },
    duration: '4.2 min',
    score: 92,
  },
  {
    id: '2',
    avatar: 'https://picsum.photos/32/32?random=2',
    name: 'Juan Martinez',
    project: 'Huergo 475',
    action: 'Brochure enviado',
    agent: { type: 'ai', name: 'Emp' },
    duration: '1.5 min',
    score: 75,
  },
  {
    id: '3',
    avatar: 'https://picsum.photos/32/32?random=3',
    name: 'Roberto Sánchez',
    project: 'Human Abasto',
    action: 'Visita agendada',
    agent: { type: 'human', name: 'Jony' },
    duration: '12 min',
    score: 95,
  },
  {
    id: '4',
    avatar: 'https://picsum.photos/32/32?random=4',
    name: 'Ana Martínez',
    project: 'Palermo Chico',
    action: 'Calificado',
    agent: { type: 'ai', name: 'Inm' },
    duration: '3.8 min',
    score: 88,
  },
  {
    id: '5',
    avatar: 'https://picsum.photos/32/32?random=5',
    name: 'Laura Fernández',
    project: 'Roccatagliata',
    action: 'Tipología enviada',
    agent: { type: 'ai', name: 'Emp' },
    duration: '2.1 min',
    score: 67,
  },
]

// ============ INBOX DATA ============

export const CONVERSATIONS: Conversation[] = [
  {
    id: '1',
    leadId: 'lead-1',
    avatar: 'https://picsum.photos/40/40?random=30',
    name: 'Juan Martinez',
    phone: '+54 11 4444-5555',
    project: 'Huergo 475',
    agentType: 'emprendimientos',
    status: 'needs_human',
    channel: 'whatsapp',
    lastMessage: 'Prefiero hablar con alguien del equipo',
    lastMessageTime: 'Hace 2 min',
    unread: true,
    isTyping: false,
    messages: [
      { id: 'm1', content: 'Hola! Vi el anuncio de Huergo 475 en Instagram', sender: 'lead', timestamp: '14:30' },
      { id: 'm2', content: '¡Hola Juan! 👋 Gracias por tu interés en Huergo 475. Es un proyecto premium en Puerto Madero con unidades de 2 y 3 ambientes. ¿Qué tipo de unidad te interesa?', sender: 'ai', senderName: 'Agente Emp', timestamp: '14:30' },
      { id: 'm3', content: 'Me interesan los 3 ambientes, cuánto sale?', sender: 'lead', timestamp: '14:32' },
      { id: 'm4', content: 'Excelente elección! Los 3 ambientes arrancan en USD 285.000. Tenemos opciones con vista al río y balcón terraza. ¿Te gustaría que te envíe el brochure con todas las tipologías?', sender: 'ai', senderName: 'Agente Emp', timestamp: '14:32' },
      { id: 'm5', content: 'Si, mandame', sender: 'lead', timestamp: '14:35' },
      { id: 'm6', content: '📎 Aquí tienes el brochure de Huergo 475. ¿Podemos coordinar una visita al showroom para que conozcas el proyecto en detalle?', sender: 'ai', senderName: 'Agente Emp', timestamp: '14:35' },
      { id: 'm7', content: 'Prefiero hablar con alguien del equipo', sender: 'lead', timestamp: '14:38' },
    ],
  },
  {
    id: '2',
    leadId: 'lead-2',
    avatar: 'https://picsum.photos/40/40?random=31',
    name: 'Carlos López',
    phone: '+54 11 5555-6666',
    project: 'Joy Patagonia',
    agentType: 'emprendimientos',
    status: 'ai_active',
    channel: 'instagram',
    lastMessage: 'Cuántas cocheras tiene?',
    lastMessageTime: 'Hace 5 min',
    unread: true,
    isTyping: true,
    messages: [
      { id: 'm1', content: 'Hola, vi el emprendimiento Joy Patagonia', sender: 'lead', timestamp: '14:20' },
      { id: 'm2', content: '¡Hola Carlos! 🏔️ Joy Patagonia es nuestro desarrollo premium en San Martín de los Andes. ¿Buscás una propiedad para inversión o uso personal?', sender: 'ai', senderName: 'Agente Emp', timestamp: '14:20' },
      { id: 'm3', content: 'Para inversión, algo que se pueda alquilar en temporada', sender: 'lead', timestamp: '14:25' },
      { id: 'm4', content: 'Perfecto! Tenemos unidades ideales para renta temporaria con administración incluida. El ROI proyectado es del 8% anual en USD. ¿Te interesa un monoambiente o un 2 ambientes?', sender: 'ai', senderName: 'Agente Emp', timestamp: '14:25' },
      { id: 'm5', content: 'Un 2 ambientes estaría bien. Cuántas cocheras tiene?', sender: 'lead', timestamp: '14:33' },
    ],
  },
  {
    id: '3',
    leadId: 'lead-3',
    avatar: 'https://picsum.photos/40/40?random=32',
    name: 'Ana Rodríguez',
    phone: '+54 11 6666-7777',
    project: 'Palermo Soho',
    agentType: 'inmuebles',
    status: 'ai_active',
    channel: 'whatsapp',
    lastMessage: 'Tiene balcón?',
    lastMessageTime: 'Hace 1 hora',
    unread: false,
    isTyping: false,
    messages: [
      { id: 'm1', content: 'Hola, busco alquilar en Palermo', sender: 'lead', timestamp: '13:00' },
      { id: 'm2', content: '¡Hola Ana! 🏠 Tenemos varias opciones de alquiler en Palermo. ¿Qué cantidad de ambientes necesitás y cuál es tu presupuesto mensual?', sender: 'ai', senderName: 'Agente Inm', timestamp: '13:00' },
      { id: 'm3', content: '2 ambientes, hasta 400 mil pesos', sender: 'lead', timestamp: '13:10' },
      { id: 'm4', content: 'Tenemos un 2 ambientes hermoso en Thames y Honduras, 65m², muy luminoso. El alquiler es de $380.000 + expensas. ¿Te interesa?', sender: 'ai', senderName: 'Agente Inm', timestamp: '13:10' },
      { id: 'm5', content: 'Tiene balcón?', sender: 'lead', timestamp: '13:35' },
    ],
  },
  {
    id: '4',
    leadId: 'lead-4',
    avatar: 'https://picsum.photos/40/40?random=33',
    name: 'Miguel Fernández',
    phone: '+54 11 7777-8888',
    project: 'Tasación Belgrano',
    agentType: 'tasaciones',
    status: 'ai_active',
    channel: 'whatsapp',
    lastMessage: 'Es un 4 ambientes con cochera',
    lastMessageTime: 'Hace 8 min',
    unread: false,
    isTyping: false,
    messages: [
      { id: 'm1', content: 'Hola, quiero tasar mi departamento', sender: 'lead', timestamp: '14:10' },
      { id: 'm2', content: '¡Hola Miguel! 📋 Con gusto te ayudamos con la tasación. ¿En qué barrio está ubicado el inmueble y qué tipo de propiedad es?', sender: 'ai', senderName: 'Agente Tas', timestamp: '14:10' },
      { id: 'm3', content: 'En Belgrano, cerca de Barrancas', sender: 'lead', timestamp: '14:15' },
      { id: 'm4', content: 'Excelente ubicación! ¿Cuántos ambientes tiene y cuenta con cochera o baulera?', sender: 'ai', senderName: 'Agente Tas', timestamp: '14:15' },
      { id: 'm5', content: 'Es un 4 ambientes con cochera', sender: 'lead', timestamp: '14:30' },
    ],
  },
  {
    id: '5',
    leadId: 'lead-5',
    avatar: 'https://picsum.photos/40/40?random=34',
    name: 'Laura Gómez',
    phone: '+54 11 8888-9999',
    project: 'Roccatagliata',
    agentType: 'emprendimientos',
    status: 'closed',
    channel: 'facebook',
    lastMessage: 'Perfecto, nos vemos el jueves',
    lastMessageTime: 'Hace 3 horas',
    unread: false,
    isTyping: false,
    messages: [
      { id: 'm1', content: 'Info sobre Roccatagliata?', sender: 'lead', timestamp: '11:00' },
      { id: 'm2', content: '¡Hola Laura! 🏢 Roccatagliata es nuestro nuevo desarrollo en Belgrano, con amenities premium y financiación en pesos. ¿Qué tipo de unidad buscás?', sender: 'ai', senderName: 'Agente Emp', timestamp: '11:00' },
      { id: 'm3', content: '2 ambientes con balcón', sender: 'lead', timestamp: '11:15' },
      { id: 'm4', content: 'Tenemos justo lo que buscás! Un 2 amb de 58m² con balcón aterrazado. ¿Te gustaría visitarlo? Tenemos disponibilidad esta semana.', sender: 'ai', senderName: 'Agente Emp', timestamp: '11:15' },
      { id: 'm5', content: 'Si, puede ser el jueves?', sender: 'lead', timestamp: '11:20' },
      { id: 'm6', content: '¡Perfecto! Te agendo para el jueves a las 15hs en nuestro showroom de Av. Cabildo 1234. Te envío la confirmación por WhatsApp. 📅', sender: 'human', senderName: 'Jony', timestamp: '11:25' },
      { id: 'm7', content: 'Perfecto, nos vemos el jueves', sender: 'lead', timestamp: '11:30' },
    ],
  },
]

export const LEAD_DETAILS: Record<string, LeadDetail> = {
  'lead-1': {
    id: 'lead-1',
    name: 'Juan Martinez',
    phone: '+54 11 4444-5555',
    email: 'juan.martinez@email.com',
    score: 85,
    interest: '3 ambientes',
    budget: '285,000',
    budgetCurrency: 'USD',
    project: 'Huergo 475',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    createdAt: '20 Ene 2026',
    history: [
      { action: 'Primer contacto', date: '20 Ene 14:30', completed: true },
      { action: 'Brochure enviado', date: '20 Ene 14:35', completed: true },
      { action: 'Pidió humano', date: '20 Ene 14:38', completed: true },
      { action: 'Contactar', date: 'Pendiente', completed: false },
    ],
  },
  'lead-2': {
    id: 'lead-2',
    name: 'Carlos López',
    phone: '+54 11 5555-6666',
    email: 'carlos.lopez@email.com',
    score: 78,
    interest: '2 ambientes inversión',
    budget: '150,000',
    budgetCurrency: 'USD',
    project: 'Joy Patagonia',
    agentType: 'emprendimientos',
    channel: 'instagram',
    createdAt: '20 Ene 2026',
    history: [
      { action: 'Primer contacto', date: '20 Ene 14:20', completed: true },
      { action: 'Calificación inicial', date: '20 Ene 14:25', completed: true },
      { action: 'Enviar tipologías', date: 'En proceso', completed: false },
    ],
  },
  'lead-3': {
    id: 'lead-3',
    name: 'Ana Rodríguez',
    phone: '+54 11 6666-7777',
    score: 65,
    interest: '2 amb alquiler',
    budget: '400,000',
    budgetCurrency: 'ARS',
    project: 'Palermo Soho',
    agentType: 'inmuebles',
    channel: 'whatsapp',
    createdAt: '20 Ene 2026',
    history: [
      { action: 'Primer contacto', date: '20 Ene 13:00', completed: true },
      { action: 'Propuesta enviada', date: '20 Ene 13:10', completed: true },
      { action: 'Coordinar visita', date: 'Pendiente', completed: false },
    ],
  },
  'lead-4': {
    id: 'lead-4',
    name: 'Miguel Fernández',
    phone: '+54 11 7777-8888',
    email: 'miguel.f@email.com',
    score: 72,
    interest: 'Tasación 4 amb',
    project: 'Tasación Belgrano',
    agentType: 'tasaciones',
    channel: 'whatsapp',
    createdAt: '20 Ene 2026',
    history: [
      { action: 'Primer contacto', date: '20 Ene 14:10', completed: true },
      { action: 'Datos recopilados', date: '20 Ene 14:30', completed: true },
      { action: 'Agendar visita', date: 'Pendiente', completed: false },
    ],
  },
  'lead-5': {
    id: 'lead-5',
    name: 'Laura Gómez',
    phone: '+54 11 8888-9999',
    email: 'laura.gomez@email.com',
    score: 92,
    interest: '2 amb con balcón',
    budget: '180,000',
    budgetCurrency: 'USD',
    project: 'Roccatagliata',
    agentType: 'emprendimientos',
    channel: 'facebook',
    createdAt: '20 Ene 2026',
    history: [
      { action: 'Primer contacto', date: '20 Ene 11:00', completed: true },
      { action: 'Brochure enviado', date: '20 Ene 11:15', completed: true },
      { action: 'Visita agendada', date: '23 Ene 15:00', completed: true },
    ],
  },
}
