import { ChartDataPoint, LeadActivity, MetricData, AttentionLead, LiveConversation, Conversation, LeadDetail, PipelineLead, PipelineColumn } from './types'

// ============ EMPRENDIMIENTOS REALES ============

export const EMPRENDIMIENTOS = {
  roccatagliata: {
    id: 'roccatagliata',
    name: 'Roccatagliata',
    location: 'Belgrano, CABA',
    description: 'Emplazado sobre un terreno de 3.500 m², conjugando la elegancia de la historia Argentina con la sofisticación de un proyecto moderno.',
    features: ['Full Amenities', 'Locales Comerciales en PB', '180 Cocheras en 3 Subsuelos'],
    tipologias: '1, 2, 3, 4 y 4 c/Dep desde 45 m² a 275 m²',
    priceRange: { min: 209657, max: 513876, currency: 'USD' },
    unitsAvailable: 35,
    totalUnits: 120,
    contact: '11-6214-8113',
    web: 'www.starargentina.com',
    amenities: ['Piscina', 'SUM', 'Terraza'],
  },
  voie: {
    id: 'voie',
    name: 'Voie Cañitas',
    location: 'Cañitas, CABA',
    description: 'Conjunto edilicio de dos frentes sobre Ortega y Gasset y Baez, PB + 10 pisos + 3 subsuelos.',
    features: ['Amenities completos', 'Local comercial', 'Cocheras y bauleras'],
    tipologias: '2 a 5 ambientes desde 91 m² a 251 m²',
    priceRange: { min: 180000, max: 450000, currency: 'USD' },
    unitsAvailable: 12,
    totalUnits: 28,
    contact: '11-6214-8113',
    web: 'www.starargentina.com',
    amenities: ['Piscina', 'Jacuzzi', 'Spa', 'Gym', 'Parrilla', 'SUM', 'Laundry'],
  },
  huergo: {
    id: 'huergo',
    name: 'Huergo 475',
    location: 'Puerto Madero, CABA',
    description: 'Proyecto premium en Puerto Madero con vistas al río y dique.',
    features: ['Vista al río', 'Amenities premium', 'Seguridad 24hs'],
    tipologias: '2 y 3 ambientes desde 65 m² a 150 m²',
    priceRange: { min: 285000, max: 650000, currency: 'USD' },
    unitsAvailable: 85,
    totalUnits: 200,
    contact: '11-6214-8113',
    web: 'www.starargentina.com',
    amenities: ['Piscina', 'Gym', 'SUM', 'Rooftop'],
  },
  humanAbasto: {
    id: 'human-abasto',
    name: 'Human Abasto Towers',
    location: 'Balvanera, CABA',
    description: 'Torres residenciales frente al Shopping Abasto con excelente conectividad.',
    features: ['Frente al Abasto', 'Subte Línea B', 'Amenities completos'],
    tipologias: '1, 2 y 3 ambientes desde 35 m² a 95 m²',
    priceRange: { min: 95000, max: 280000, currency: 'USD' },
    unitsAvailable: 45,
    totalUnits: 180,
    contact: '11-6214-8113',
    web: 'www.starargentina.com',
    amenities: ['Piscina', 'Gym', 'Laundry', 'Coworking'],
  },
  joyPatagonia: {
    id: 'joy-patagonia',
    name: 'Joy Patagonia',
    location: 'San Martín de los Andes',
    description: 'Desarrollo premium en la Patagonia con administración para renta temporaria.',
    features: ['Renta temporaria', 'Administración incluida', 'ROI 8% anual'],
    tipologias: 'Monoambientes y 2 ambientes desde 40 m² a 75 m²',
    priceRange: { min: 120000, max: 220000, currency: 'USD' },
    unitsAvailable: 18,
    totalUnits: 60,
    contact: '11-6214-8113',
    web: 'www.starargentina.com',
    amenities: ['Spa', 'Restaurante', 'Ski room'],
  },
  btnPinamar: {
    id: 'btn-pinamar',
    name: 'BTN Pinamar',
    location: 'Pinamar, Buenos Aires',
    description: 'Complejo de departamentos a metros del mar en Pinamar.',
    features: ['A 200m del mar', 'Ideal inversión', 'Temporada alta'],
    tipologias: '1 y 2 ambientes desde 35 m² a 60 m²',
    priceRange: { min: 85000, max: 150000, currency: 'USD' },
    unitsAvailable: 22,
    totalUnits: 48,
    contact: '11-6214-8113',
    web: 'www.starargentina.com',
    amenities: ['Piscina', 'Parrilla', 'Solarium'],
  },
  puertoQuetzal: {
    id: 'puerto-quetzal',
    name: 'Puerto Quetzal',
    location: 'Tigre, Buenos Aires',
    description: 'Barrio náutico con amarras privadas en el Delta del Tigre.',
    features: ['Amarra privada', 'Seguridad 24hs', 'Club house'],
    tipologias: 'Casas y dptos desde 80 m² a 200 m²',
    priceRange: { min: 180000, max: 450000, currency: 'USD' },
    unitsAvailable: 8,
    totalUnits: 32,
    contact: '11-6214-8113',
    web: 'www.starargentina.com',
    amenities: ['Club House', 'Piscina', 'Cancha de tenis', 'Muelle'],
  },
}

export const METRICS: MetricData[] = [
  {
    title: "Leads Totales",
    value: "127,482",
    change: "+23%",
    isPositive: true,
  },
  {
    title: "Conversaciones Activas",
    value: "42",
    change: "+4%",
    isPositive: true,
  },
  {
    title: "Tasa de Conversión",
    value: "68.7%",
    change: "+0.4%",
    isPositive: true,
  },
  {
    title: "Calificados Hoy",
    value: "18",
    change: "",
    isPositive: true,
  },
]

export const CHART_DATA: ChartDataPoint[] = [
  { date: 'Ene 13', total: 4000, qualified: 2400 },
  { date: 'Ene 14', total: 5800, qualified: 3200 },
  { date: 'Ene 15', total: 4200, qualified: 3800 },
  { date: 'Ene 16', total: 2800, qualified: 2100 },
  { date: 'Ene 17', total: 5100, qualified: 2800 },
  { date: 'Ene 18', total: 4500, qualified: 2100 },
  { date: 'Ene 19', total: 6800, qualified: 4200 },
  { date: 'Ene 20', total: 5900, qualified: 5100 },
]

export const ATTENTION_LEADS: AttentionLead[] = [
  {
    id: '1',
    avatar: '',
    name: 'Juan Martinez',
    reason: 'human_requested',
    reasonText: 'Pidió hablar con humano',
    project: 'Roccatagliata',
    timeAgo: 'Hace 5 min',
    score: 85,
  },
  {
    id: '2',
    avatar: '',
    name: 'María López',
    reason: 'high_score',
    reasonText: 'Score 95, sin contactar',
    project: 'Huergo 475',
    timeAgo: 'Hace 2 horas',
    score: 95,
  },
  {
    id: '3',
    avatar: '',
    name: 'Carlos Ruiz',
    reason: 'no_response',
    reasonText: '2 días sin respuesta',
    project: 'Human Abasto',
    timeAgo: 'Hace 2 días',
    score: 72,
  },
]

export const LIVE_CONVERSATIONS: LiveConversation[] = [
  {
    id: '1',
    avatar: '',
    name: 'Juan Martinez',
    project: 'Roccatagliata',
    status: 'typing',
    lastActivity: 'Escribiendo...',
    agentType: 'emprendimientos',
  },
  {
    id: '2',
    avatar: '',
    name: 'Carlos López',
    project: 'Huergo 475',
    status: 'waiting',
    lastActivity: '2 min',
    agentType: 'emprendimientos',
  },
  {
    id: '3',
    avatar: '',
    name: 'Ana Rodríguez',
    project: 'Voie Cañitas',
    status: 'waiting',
    lastActivity: '5 min',
    agentType: 'emprendimientos',
  },
  {
    id: '4',
    avatar: '',
    name: 'Miguel Fernández',
    project: 'Tasación Belgrano',
    status: 'waiting',
    lastActivity: '8 min',
    agentType: 'tasaciones',
  },
]

export const RECENT_ACTIVITY: LeadActivity[] = [
  {
    id: '1',
    avatar: '',
    name: 'María González',
    project: 'Roccatagliata',
    action: 'Calificado',
    agent: { type: 'ai', name: 'Emp' },
    duration: '4.2 min',
    score: 92,
  },
  {
    id: '2',
    avatar: '',
    name: 'Juan Martinez',
    project: 'Huergo 475',
    action: 'Brochure enviado',
    agent: { type: 'ai', name: 'Emp' },
    duration: '1.5 min',
    score: 75,
  },
  {
    id: '3',
    avatar: '',
    name: 'Roberto Sánchez',
    project: 'Human Abasto',
    action: 'Visita agendada',
    agent: { type: 'human', name: 'Jony' },
    duration: '12 min',
    score: 95,
  },
  {
    id: '4',
    avatar: '',
    name: 'Ana Martínez',
    project: 'Voie Cañitas',
    action: 'Calificado',
    agent: { type: 'ai', name: 'Emp' },
    duration: '3.8 min',
    score: 88,
  },
  {
    id: '5',
    avatar: '',
    name: 'Laura Fernández',
    project: 'Roccatagliata',
    action: 'Tipología enviada',
    agent: { type: 'ai', name: 'Emp' },
    duration: '2.1 min',
    score: 67,
  },
]

// ============ INBOX DATA ============

export const CONVERSATIONS: Conversation[] = [
  {
    id: '1',
    leadId: 'lead-1',
    avatar: '',
    name: 'Juan Martinez',
    phone: '+54 11 4444-5555',
    project: 'Huergo 475',
    agentType: 'emprendimientos',
    status: 'needs_human',
    channel: 'whatsapp',
    lastMessage: 'Prefiero hablar con alguien del equipo',
    lastMessageTime: 'Hace 2 min',
    unread: true,
    isTyping: false,
    messages: [
      { id: 'm1', content: 'Hola! Vi el anuncio de Huergo 475 en Instagram', sender: 'lead', timestamp: '14:30' },
      { id: 'm2', content: '¡Hola Juan! 👋 Gracias por tu interés en Huergo 475. Es un proyecto premium en Puerto Madero con unidades de 2 y 3 ambientes con vista al río. ¿Qué tipo de unidad te interesa?', sender: 'ai', senderName: 'Agente Emp', timestamp: '14:30' },
      { id: 'm3', content: 'Me interesan los 3 ambientes, cuánto sale?', sender: 'lead', timestamp: '14:32' },
      { id: 'm4', content: 'Excelente elección! Los 3 ambientes arrancan en USD 285.000 y van hasta USD 450.000 según el piso y la vista. Tenemos opciones con vista al río y balcón terraza. ¿Te gustaría que te envíe el brochure con todas las tipologías?', sender: 'ai', senderName: 'Agente Emp', timestamp: '14:32' },
      { id: 'm5', content: 'Si, mandame', sender: 'lead', timestamp: '14:35' },
      { id: 'm6', content: '📎 Aquí tienes el brochure de Huergo 475. ¿Podemos coordinar una visita al showroom para que conozcas el proyecto en detalle?', sender: 'ai', senderName: 'Agente Emp', timestamp: '14:35' },
      { id: 'm7', content: 'Prefiero hablar con alguien del equipo', sender: 'lead', timestamp: '14:38' },
    ],
  },
  {
    id: '2',
    leadId: 'lead-2',
    avatar: '',
    name: 'Carlos López',
    phone: '+54 11 5555-6666',
    project: 'Joy Patagonia',
    agentType: 'emprendimientos',
    status: 'ai_active',
    channel: 'instagram',
    lastMessage: 'Cuántas cocheras tiene?',
    lastMessageTime: 'Hace 5 min',
    unread: true,
    isTyping: true,
    messages: [
      { id: 'm1', content: 'Hola, vi el emprendimiento Joy Patagonia', sender: 'lead', timestamp: '14:20' },
      { id: 'm2', content: '¡Hola Carlos! 🏔️ Joy Patagonia es nuestro desarrollo premium en San Martín de los Andes con administración para renta temporaria incluida. El ROI proyectado es del 8% anual en USD. ¿Buscás una propiedad para inversión o uso personal?', sender: 'ai', senderName: 'Agente Emp', timestamp: '14:20' },
      { id: 'm3', content: 'Para inversión, algo que se pueda alquilar en temporada', sender: 'lead', timestamp: '14:25' },
      { id: 'm4', content: 'Perfecto! Tenemos unidades ideales para renta temporaria. Los monoambientes arrancan en USD 120.000 y los 2 ambientes desde USD 180.000. ¿Te interesa un monoambiente o un 2 ambientes?', sender: 'ai', senderName: 'Agente Emp', timestamp: '14:25' },
      { id: 'm5', content: 'Un 2 ambientes estaría bien. Cuántas cocheras tiene?', sender: 'lead', timestamp: '14:33' },
    ],
  },
  {
    id: '3',
    leadId: 'lead-3',
    avatar: '',
    name: 'Ana Rodríguez',
    phone: '+54 11 6666-7777',
    project: 'Voie Cañitas',
    agentType: 'emprendimientos',
    status: 'ai_active',
    channel: 'whatsapp',
    lastMessage: 'Tiene balcón?',
    lastMessageTime: 'Hace 1 hora',
    unread: false,
    isTyping: false,
    messages: [
      { id: 'm1', content: 'Hola, busco comprar en Cañitas', sender: 'lead', timestamp: '13:00' },
      { id: 'm2', content: '¡Hola Ana! 🏠 Tenemos Voie Cañitas, un desarrollo de dos frentes sobre Ortega y Gasset y Baez con PB + 10 pisos. Amenities completos: Piscina, Jacuzzi, Spa, Gym, Parrilla, SUM y Laundry. ¿Qué cantidad de ambientes necesitás?', sender: 'ai', senderName: 'Agente Emp', timestamp: '13:00' },
      { id: 'm3', content: '2 ambientes, hasta 200 mil dólares', sender: 'lead', timestamp: '13:10' },
      { id: 'm4', content: 'Tenemos 2 ambientes con escritorio de 98 m² totales, muy luminosos. El rango de precios para estas unidades está dentro de tu presupuesto. ¿Te interesa?', sender: 'ai', senderName: 'Agente Emp', timestamp: '13:10' },
      { id: 'm5', content: 'Tiene balcón?', sender: 'lead', timestamp: '13:35' },
    ],
  },
  {
    id: '4',
    leadId: 'lead-4',
    avatar: '',
    name: 'Miguel Fernández',
    phone: '+54 11 7777-8888',
    project: 'Tasación Belgrano',
    agentType: 'tasaciones',
    status: 'ai_active',
    channel: 'whatsapp',
    lastMessage: 'Es un 4 ambientes con cochera',
    lastMessageTime: 'Hace 8 min',
    unread: false,
    isTyping: false,
    messages: [
      { id: 'm1', content: 'Hola, quiero tasar mi departamento', sender: 'lead', timestamp: '14:10' },
      { id: 'm2', content: '¡Hola Miguel! 📋 Con gusto te ayudamos con la tasación. ¿En qué barrio está ubicado el inmueble y qué tipo de propiedad es?', sender: 'ai', senderName: 'Agente Tas', timestamp: '14:10' },
      { id: 'm3', content: 'En Belgrano, cerca de Barrancas', sender: 'lead', timestamp: '14:15' },
      { id: 'm4', content: 'Excelente ubicación! ¿Cuántos ambientes tiene y cuenta con cochera o baulera?', sender: 'ai', senderName: 'Agente Tas', timestamp: '14:15' },
      { id: 'm5', content: 'Es un 4 ambientes con cochera', sender: 'lead', timestamp: '14:30' },
    ],
  },
  {
    id: '5',
    leadId: 'lead-5',
    avatar: '',
    name: 'Laura Gómez',
    phone: '+54 11 8888-9999',
    project: 'Roccatagliata',
    agentType: 'emprendimientos',
    status: 'closed',
    channel: 'facebook',
    lastMessage: 'Perfecto, nos vemos el jueves',
    lastMessageTime: 'Hace 3 horas',
    unread: false,
    isTyping: false,
    messages: [
      { id: 'm1', content: 'Info sobre Roccatagliata?', sender: 'lead', timestamp: '11:00' },
      { id: 'm2', content: '¡Hola Laura! 🏢 Roccatagliata es nuestro desarrollo premium en Belgrano sobre un terreno de 3.500 m². Full amenities, 180 cocheras, y unidades desde 1 a 4 ambientes (45 m² a 275 m²). Precios desde USD 209.657. ¿Qué tipo de unidad buscás?', sender: 'ai', senderName: 'Agente Emp', timestamp: '11:00' },
      { id: 'm3', content: '2 ambientes con balcón', sender: 'lead', timestamp: '11:15' },
      { id: 'm4', content: 'Tenemos 2 ambientes de 54 m² cubiertos con balcón desde USD 259.260. ¿Te gustaría visitarlo? Tenemos disponibilidad esta semana.', sender: 'ai', senderName: 'Agente Emp', timestamp: '11:15' },
      { id: 'm5', content: 'Si, puede ser el jueves?', sender: 'lead', timestamp: '11:20' },
      { id: 'm6', content: '¡Perfecto! Te agendo para el jueves a las 15hs en nuestro showroom. Te envío la confirmación por WhatsApp. 📅', sender: 'human', senderName: 'Jony', timestamp: '11:25' },
      { id: 'm7', content: 'Perfecto, nos vemos el jueves', sender: 'lead', timestamp: '11:30' },
    ],
  },
  {
    id: '6',
    leadId: 'lead-6',
    avatar: '',
    name: 'Roberto Sánchez',
    phone: '+54 11 2222-3333',
    project: 'Human Abasto',
    agentType: 'emprendimientos',
    status: 'ai_active',
    channel: 'whatsapp',
    lastMessage: 'Qué financiación tienen?',
    lastMessageTime: 'Hace 15 min',
    unread: false,
    isTyping: false,
    messages: [
      { id: 'm1', content: 'Hola, vi Human Abasto en la web', sender: 'lead', timestamp: '14:00' },
      { id: 'm2', content: '¡Hola Roberto! 🏢 Human Abasto Towers está frente al Shopping Abasto con excelente conectividad (Subte Línea B). Unidades de 1, 2 y 3 ambientes desde USD 95.000. ¿Qué tipo de unidad te interesa?', sender: 'ai', senderName: 'Agente Emp', timestamp: '14:00' },
      { id: 'm3', content: 'Un 2 ambientes, qué financiación tienen?', sender: 'lead', timestamp: '14:15' },
    ],
  },
]

export const LEAD_DETAILS: Record<string, LeadDetail> = {
  'lead-1': {
    id: 'lead-1',
    name: 'Juan Martinez',
    phone: '+54 11 4444-5555',
    email: 'juan.martinez@email.com',
    score: 85,
    interest: '3 ambientes vista río',
    budget: '285,000 - 450,000',
    budgetCurrency: 'USD',
    project: 'Huergo 475',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    createdAt: '20 Ene 2026',
    history: [
      { action: 'Primer contacto', date: '20 Ene 14:30', completed: true },
      { action: 'Brochure enviado', date: '20 Ene 14:35', completed: true },
      { action: 'Pidió humano', date: '20 Ene 14:38', completed: true },
      { action: 'Contactar', date: 'Pendiente', completed: false },
    ],
  },
  'lead-2': {
    id: 'lead-2',
    name: 'Carlos López',
    phone: '+54 11 5555-6666',
    email: 'carlos.lopez@email.com',
    score: 78,
    interest: '2 amb inversión',
    budget: '180,000',
    budgetCurrency: 'USD',
    project: 'Joy Patagonia',
    agentType: 'emprendimientos',
    channel: 'instagram',
    createdAt: '20 Ene 2026',
    history: [
      { action: 'Primer contacto', date: '20 Ene 14:20', completed: true },
      { action: 'Calificación inicial', date: '20 Ene 14:25', completed: true },
      { action: 'Enviar tipologías', date: 'En proceso', completed: false },
    ],
  },
  'lead-3': {
    id: 'lead-3',
    name: 'Ana Rodríguez',
    phone: '+54 11 6666-7777',
    score: 72,
    interest: '2 amb con escritorio',
    budget: '200,000',
    budgetCurrency: 'USD',
    project: 'Voie Cañitas',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    createdAt: '20 Ene 2026',
    history: [
      { action: 'Primer contacto', date: '20 Ene 13:00', completed: true },
      { action: 'Info enviada', date: '20 Ene 13:10', completed: true },
      { action: 'Coordinar visita', date: 'Pendiente', completed: false },
    ],
  },
  'lead-4': {
    id: 'lead-4',
    name: 'Miguel Fernández',
    phone: '+54 11 7777-8888',
    email: 'miguel.f@email.com',
    score: 72,
    interest: 'Tasación 4 amb',
    project: 'Tasación Belgrano',
    agentType: 'tasaciones',
    channel: 'whatsapp',
    createdAt: '20 Ene 2026',
    history: [
      { action: 'Primer contacto', date: '20 Ene 14:10', completed: true },
      { action: 'Datos recopilados', date: '20 Ene 14:30', completed: true },
      { action: 'Agendar visita', date: 'Pendiente', completed: false },
    ],
  },
  'lead-5': {
    id: 'lead-5',
    name: 'Laura Gómez',
    phone: '+54 11 8888-9999',
    email: 'laura.gomez@email.com',
    score: 92,
    interest: '2 amb con balcón',
    budget: '259,260',
    budgetCurrency: 'USD',
    project: 'Roccatagliata',
    agentType: 'emprendimientos',
    channel: 'facebook',
    createdAt: '20 Ene 2026',
    history: [
      { action: 'Primer contacto', date: '20 Ene 11:00', completed: true },
      { action: 'Brochure enviado', date: '20 Ene 11:15', completed: true },
      { action: 'Visita agendada', date: '23 Ene 15:00', completed: true },
    ],
  },
  'lead-6': {
    id: 'lead-6',
    name: 'Roberto Sánchez',
    phone: '+54 11 2222-3333',
    email: 'roberto.sanchez@email.com',
    score: 68,
    interest: '2 amb',
    budget: '150,000',
    budgetCurrency: 'USD',
    project: 'Human Abasto',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    createdAt: '20 Ene 2026',
    history: [
      { action: 'Primer contacto', date: '20 Ene 14:00', completed: true },
      { action: 'Consulta financiación', date: '20 Ene 14:15', completed: true },
      { action: 'Responder', date: 'Pendiente', completed: false },
    ],
  },
}

// ============ PIPELINE DATA ============

export const PIPELINE_COLUMNS: PipelineColumn[] = [
  { id: 'nuevo', title: 'Nuevo', color: 'bg-gray-500' },
  { id: 'calificado', title: 'Calificado', color: 'bg-blue-500' },
  { id: 'contactado', title: 'Contactado', color: 'bg-purple-500' },
  { id: 'visita', title: 'Visita', color: 'bg-amber-500' },
  { id: 'cierre', title: 'Cierre', color: 'bg-emerald-500' },
]

export const PIPELINE_LEADS: PipelineLead[] = [
  // NUEVO (5)
  {
    id: 'pl-1',
    name: 'Martín Aguirre',
    phone: '+54 11 1111-2222',
    project: 'Roccatagliata',
    agentType: 'emprendimientos',
    channel: 'instagram',
    score: 45,
    interest: '2 ambientes',
    stage: 'nuevo',
    createdAt: '20 Ene 2026',
    lastActivity: 'Hace 10 min',
  },
  {
    id: 'pl-2',
    name: 'Sofía Peralta',
    phone: '+54 11 2222-3333',
    project: 'Huergo 475',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    score: 52,
    interest: '3 ambientes',
    stage: 'nuevo',
    createdAt: '20 Ene 2026',
    lastActivity: 'Hace 25 min',
  },
  {
    id: 'pl-3',
    name: 'Diego Romero',
    phone: '+54 11 3333-4444',
    project: 'Human Abasto',
    agentType: 'emprendimientos',
    channel: 'facebook',
    score: 38,
    interest: '1 ambiente',
    stage: 'nuevo',
    createdAt: '19 Ene 2026',
    lastActivity: 'Hace 1 hora',
  },
  {
    id: 'pl-4',
    name: 'Valentina Costa',
    phone: '+54 11 4444-5555',
    project: 'Voie Cañitas',
    agentType: 'emprendimientos',
    channel: 'instagram',
    score: 41,
    interest: '3 ambientes',
    stage: 'nuevo',
    createdAt: '19 Ene 2026',
    lastActivity: 'Hace 2 horas',
  },
  {
    id: 'pl-5',
    name: 'Nicolás Herrera',
    phone: '+54 11 5555-6666',
    project: 'Joy Patagonia',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    score: 55,
    interest: 'Monoambiente inversión',
    stage: 'nuevo',
    createdAt: '19 Ene 2026',
    lastActivity: 'Hace 3 horas',
  },
  // CALIFICADO (5)
  {
    id: 'pl-6',
    name: 'Juan Martinez',
    phone: '+54 11 4444-5555',
    email: 'juan.martinez@email.com',
    project: 'Huergo 475',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    score: 85,
    budget: '350,000',
    budgetCurrency: 'USD',
    interest: '3 amb vista río',
    stage: 'calificado',
    createdAt: '20 Ene 2026',
    lastActivity: 'Hace 5 min',
    notes: 'Pidió hablar con humano',
  },
  {
    id: 'pl-7',
    name: 'Carlos López',
    phone: '+54 11 5555-6666',
    email: 'carlos.lopez@email.com',
    project: 'Joy Patagonia',
    agentType: 'emprendimientos',
    channel: 'instagram',
    score: 78,
    budget: '180,000',
    budgetCurrency: 'USD',
    interest: '2 amb inversión',
    stage: 'calificado',
    createdAt: '20 Ene 2026',
    lastActivity: 'Hace 5 min',
  },
  {
    id: 'pl-8',
    name: 'María López',
    phone: '+54 11 6666-7777',
    email: 'maria.lopez@email.com',
    project: 'Huergo 475',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    score: 95,
    budget: '450,000',
    budgetCurrency: 'USD',
    interest: '3 amb premium',
    stage: 'calificado',
    createdAt: '19 Ene 2026',
    lastActivity: 'Hace 2 horas',
    notes: 'Score alto, priorizar',
  },
  {
    id: 'pl-9',
    name: 'Ana Rodríguez',
    phone: '+54 11 6666-7777',
    project: 'Voie Cañitas',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    score: 72,
    budget: '200,000',
    budgetCurrency: 'USD',
    interest: '2 amb con escritorio',
    stage: 'calificado',
    createdAt: '20 Ene 2026',
    lastActivity: 'Hace 1 hora',
  },
  {
    id: 'pl-10',
    name: 'Pedro García',
    phone: '+54 11 7777-8888',
    email: 'pedro.garcia@email.com',
    project: 'Roccatagliata',
    agentType: 'emprendimientos',
    channel: 'facebook',
    score: 81,
    budget: '320,000',
    budgetCurrency: 'USD',
    interest: '3 amb con dep',
    stage: 'calificado',
    createdAt: '18 Ene 2026',
    lastActivity: 'Hace 1 día',
  },
  // CONTACTADO (3)
  {
    id: 'pl-11',
    name: 'Carlos Ruiz',
    phone: '+54 11 8888-9999',
    email: 'carlos.ruiz@email.com',
    project: 'Human Abasto',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    score: 72,
    budget: '150,000',
    budgetCurrency: 'USD',
    interest: '2 amb',
    stage: 'contactado',
    createdAt: '18 Ene 2026',
    lastActivity: 'Hace 2 días',
    assignedTo: 'Jony',
    notes: '2 días sin respuesta',
  },
  {
    id: 'pl-12',
    name: 'Roberto Sánchez',
    phone: '+54 11 2222-3333',
    email: 'roberto.sanchez@email.com',
    project: 'Human Abasto',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    score: 68,
    budget: '150,000',
    budgetCurrency: 'USD',
    interest: '2 amb',
    stage: 'contactado',
    createdAt: '20 Ene 2026',
    lastActivity: 'Hace 15 min',
    assignedTo: 'Jony',
  },
  {
    id: 'pl-13',
    name: 'Luciana Torres',
    phone: '+54 11 9999-0000',
    email: 'luciana.torres@email.com',
    project: 'BTN Pinamar',
    agentType: 'emprendimientos',
    channel: 'instagram',
    score: 76,
    budget: '120,000',
    budgetCurrency: 'USD',
    interest: '2 amb playa',
    stage: 'contactado',
    createdAt: '17 Ene 2026',
    lastActivity: 'Hace 1 día',
    assignedTo: 'María',
  },
  // VISITA (3)
  {
    id: 'pl-14',
    name: 'Laura Gómez',
    phone: '+54 11 8888-9999',
    email: 'laura.gomez@email.com',
    project: 'Roccatagliata',
    agentType: 'emprendimientos',
    channel: 'facebook',
    score: 92,
    budget: '259,260',
    budgetCurrency: 'USD',
    interest: '2 amb con balcón',
    stage: 'visita',
    createdAt: '20 Ene 2026',
    lastActivity: 'Hoy',
    assignedTo: 'Jony',
    scheduledDate: '23 Ene 15:00',
    notes: 'Visita confirmada',
  },
  {
    id: 'pl-15',
    name: 'Miguel Fernández',
    phone: '+54 11 7777-8888',
    email: 'miguel.f@email.com',
    project: 'Tasación Belgrano',
    agentType: 'tasaciones',
    channel: 'whatsapp',
    score: 72,
    interest: 'Tasación 4 amb',
    stage: 'visita',
    createdAt: '20 Ene 2026',
    lastActivity: 'Hace 8 min',
    assignedTo: 'Pablo',
    scheduledDate: '22 Ene 10:00',
    notes: 'Coordinar visita tasación',
  },
  {
    id: 'pl-16',
    name: 'Fernando Díaz',
    phone: '+54 11 1234-5678',
    email: 'fernando.diaz@email.com',
    project: 'Voie Cañitas',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    score: 88,
    budget: '280,000',
    budgetCurrency: 'USD',
    interest: '3 amb con terraza',
    stage: 'visita',
    createdAt: '16 Ene 2026',
    lastActivity: 'Ayer',
    assignedTo: 'Jony',
    scheduledDate: '24 Ene 16:00',
    notes: 'Segunda visita programada',
  },
  // CIERRE (2)
  {
    id: 'pl-17',
    name: 'María González',
    phone: '+54 11 5678-1234',
    email: 'maria.gonzalez@email.com',
    project: 'Roccatagliata',
    agentType: 'emprendimientos',
    channel: 'whatsapp',
    score: 98,
    budget: '380,000',
    budgetCurrency: 'USD',
    interest: '3 amb piso alto',
    stage: 'cierre',
    createdAt: '10 Ene 2026',
    lastActivity: 'Hoy',
    assignedTo: 'Jony',
    notes: 'Firma de boleto viernes',
  },
  {
    id: 'pl-18',
    name: 'Alejandro Vega',
    phone: '+54 11 8765-4321',
    email: 'alejandro.vega@email.com',
    project: 'Huergo 475',
    agentType: 'emprendimientos',
    channel: 'instagram',
    score: 96,
    budget: '520,000',
    budgetCurrency: 'USD',
    interest: '4 amb vista panorámica',
    stage: 'cierre',
    createdAt: '8 Ene 2026',
    lastActivity: 'Ayer',
    assignedTo: 'María',
    notes: 'Negociando condiciones de pago',
  },
]
